version: "1"
projects:
- name: Data Crawl Hub
  environments:
  - name: Production
    services:
    - type: web
      name: auto-quet-sat-lo
      runtime: node
      repo: https://github.com/hoangthanh2006/auto-quet-sat-lo
      plan: free
      region: oregon
      buildCommand: npm run build
      startCommand: npm start
      autoDeployTrigger: commit
      rootDir: server
      envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/server/.cache/puppeteer
