# Exported from Render on 2026-02-01T08:01:43Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Data-crawl
      runtime: node
      repo: https://github.com/hoangthanh2006/Data-crawl
      plan: free
      region: oregon
      buildCommand: npm install
      startCommand: npm start
      autoDeployTrigger: commit
      rootDir: server
